[package]
name = "attyvo"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5", features = ["derive"] }
daemonize-me = "2.0.2"
exec = "0.3.1"
libc = "0.2.174"
unix-named-pipe = "0.2.0"
